# Generated by Django 3.2 on 2023-04-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodel',
            name='title',
            field=models.CharField(default='Title', max_length=25),
        ),
    ]
