# Generated by Django 3.2 on 2023-04-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_alter_contentmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodel',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
