# Generated by Django 3.2 on 2023-04-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_alter_contentmodel_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodel',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
